//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G9Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("G9Common.Resource.LogMessage", typeof(LogMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountAdded.
        /// </summary>
        public static string AccountAdded {
            get {
                return ResourceManager.GetString("AccountAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountAndSessionCreated.
        /// </summary>
        public static string AccountAndSessionCreated {
            get {
                return ResourceManager.GetString("AccountAndSessionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action send command call back cannot be null.
        /// </summary>
        public static string ActionSendCommandCallBackCannotBeNull {
            get {
                return ResourceManager.GetString("ActionSendCommandCallBackCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command add successfully.
        /// </summary>
        public static string AddCommandSuccessfully {
            get {
                return ResourceManager.GetString("AddCommandSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArgumentNotCorrect.
        /// </summary>
        public static string ArgumentNotCorrect {
            get {
                return ResourceManager.GetString("ArgumentNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArgumentXNotCorrect.
        /// </summary>
        public static string ArgumentXNotCorrect {
            get {
                return ResourceManager.GetString("ArgumentXNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The problem in the authorization process.
        /// </summary>
        public static string AuthorizationFail {
            get {
                return ResourceManager.GetString("AuthorizationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization approved correctly.
        /// </summary>
        public static string AuthorizationSuccess {
            get {
                return ResourceManager.GetString("AuthorizationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BufferSize.
        /// </summary>
        public static string BufferSize {
            get {
                return ResourceManager.GetString("BufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CantStopStoppedServer.
        /// </summary>
        public static string CantStopStoppedServer {
            get {
                return ResourceManager.GetString("CantStopStoppedServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate does not have a private key.
        /// </summary>
        public static string CertificateDoseNotHavePrivateKey {
            get {
                return ResourceManager.GetString("CertificateDoseNotHavePrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate is not exportable. Use &apos;X509KeyStorageFlags.Exportable&apos; when creating &apos;X509Certificate2&apos;..
        /// </summary>
        public static string CertificateIsNotExportable {
            get {
                return ResourceManager.GetString("CertificateIsNotExportable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelopes are not a complete request for body modification.
        /// </summary>
        public static string ChangeBodyMultiPacketNotFill {
            get {
                return ResourceManager.GetString("ChangeBodyMultiPacketNotFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientPing.
        /// </summary>
        public static string ClientPing {
            get {
                return ResourceManager.GetString("ClientPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientPingDateTime.
        /// </summary>
        public static string ClientPingDateTime {
            get {
                return ResourceManager.GetString("ClientPingDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientSessionIdentity.
        /// </summary>
        public static string ClientSessionIdentity {
            get {
                return ResourceManager.GetString("ClientSessionIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is implemented as SSL. But the client is connected to it without a certificate..
        /// </summary>
        public static string ClientWithOutCertificate {
            get {
                return ResourceManager.GetString("ClientWithOutCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseReason.
        /// </summary>
        public static string CloseReason {
            get {
                return ResourceManager.GetString("CloseReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandEcho.
        /// </summary>
        public static string CommandEcho {
            get {
                return ResourceManager.GetString("CommandEcho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandLengthError.
        /// </summary>
        public static string CommandLengthError {
            get {
                return ResourceManager.GetString("CommandLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandName.
        /// </summary>
        public static string CommandName {
            get {
                return ResourceManager.GetString("CommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandNotFound.
        /// </summary>
        public static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandSendType.
        /// </summary>
        public static string CommandSendType {
            get {
                return ResourceManager.GetString("CommandSendType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandSendTypeNotCorrect.
        /// </summary>
        public static string CommandSendTypeNotCorrect {
            get {
                return ResourceManager.GetString("CommandSendTypeNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommanTestSendReceive.
        /// </summary>
        public static string CommanTestSendReceive {
            get {
                return ResourceManager.GetString("CommanTestSendReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country code like &quot;US&quot; should be 2 characters.
        /// </summary>
        public static string CountryCodeIsTwoChar {
            get {
                return ResourceManager.GetString("CountryCodeIsTwoChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateAndInitializeClient.
        /// </summary>
        public static string CreateAndInitializeClient {
            get {
                return ResourceManager.GetString("CreateAndInitializeClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateAndInitializeServer.
        /// </summary>
        public static string CreateAndInitializeServer {
            get {
                return ResourceManager.GetString("CreateAndInitializeServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNewAccount.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentSessionCount.
        /// </summary>
        public static string CurrentSessionCount {
            get {
                return ResourceManager.GetString("CurrentSessionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataLength.
        /// </summary>
        public static string DataLength {
            get {
                return ResourceManager.GetString("DataLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisableCommandTestModeForAllClients.
        /// </summary>
        public static string DisableCommandTestModeForAllClients {
            get {
                return ResourceManager.GetString("DisableCommandTestModeForAllClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisableCommandTestModeForSingleSession.
        /// </summary>
        public static string DisableCommandTestModeForSingleSession {
            get {
                return ResourceManager.GetString("DisableCommandTestModeForSingleSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnableCommandTestModeForAllClients.
        /// </summary>
        public static string EnableCommandTestModeForAllClients {
            get {
                return ResourceManager.GetString("EnableCommandTestModeForAllClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnableCommandTestModeForSingleSession.
        /// </summary>
        public static string EnableCommandTestModeForSingleSession {
            get {
                return ResourceManager.GetString("EnableCommandTestModeForSingleSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorInRunningCommand.
        /// </summary>
        public static string ErrorInRunningCommand {
            get {
                return ResourceManager.GetString("ErrorInRunningCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hashed password must be 32 characters.
        /// </summary>
        public static string ExtraPassIsNot32Char {
            get {
                return ResourceManager.GetString("ExtraPassIsNot32Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail in add command because account generic type is not equal between server and command.
        /// </summary>
        public static string FailAddCommandForGenericAccountType {
            get {
                return ResourceManager.GetString("FailAddCommandForGenericAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailBindAndListenSocket.
        /// </summary>
        public static string FailBindAndListenSocket {
            get {
                return ResourceManager.GetString("FailBindAndListenSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailClientReceive.
        /// </summary>
        public static string FailClientReceive {
            get {
                return ResourceManager.GetString("FailClientReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailClinetConnection.
        /// </summary>
        public static string FailClinetConnection {
            get {
                return ResourceManager.GetString("FailClinetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailedOperation.
        /// </summary>
        public static string FailedOperation {
            get {
                return ResourceManager.GetString("FailedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailGeneratePacket.
        /// </summary>
        public static string FailGeneratePacket {
            get {
                return ResourceManager.GetString("FailGeneratePacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailReceiveClientFromServer.
        /// </summary>
        public static string FailReceiveClientFromServer {
            get {
                return ResourceManager.GetString("FailReceiveClientFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailRequestSendData.
        /// </summary>
        public static string FailRequestSendData {
            get {
                return ResourceManager.GetString("FailRequestSendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailSendComandByName.
        /// </summary>
        public static string FailSendComandByName {
            get {
                return ResourceManager.GetString("FailSendComandByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailSendComandByNameAsync.
        /// </summary>
        public static string FailSendComandByNameAsync {
            get {
                return ResourceManager.GetString("FailSendComandByNameAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailSendComandByNameToAll.
        /// </summary>
        public static string FailSendComandByNameToAll {
            get {
                return ResourceManager.GetString("FailSendComandByNameToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailSendComandByNameToAllAsync.
        /// </summary>
        public static string FailSendComandByNameToAllAsync {
            get {
                return ResourceManager.GetString("FailSendComandByNameToAllAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailStopServer.
        /// </summary>
        public static string FailStopServer {
            get {
                return ResourceManager.GetString("FailStopServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailtOnWaitForConnection.
        /// </summary>
        public static string FailtOnWaitForConnection {
            get {
                return ResourceManager.GetString("FailtOnWaitForConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FakeAccountAndSessionCreated.
        /// </summary>
        public static string FakeAccountAndSessionCreated {
            get {
                return ResourceManager.GetString("FakeAccountAndSessionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpAddress.
        /// </summary>
        public static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastCommandUsed.
        /// </summary>
        public static string LastCommandUsed {
            get {
                return ResourceManager.GetString("LastCommandUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastCommandUsedDateTime.
        /// </summary>
        public static string LastCommandUsedDateTime {
            get {
                return ResourceManager.GetString("LastCommandUsedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LengthEntered.
        /// </summary>
        public static string LengthEntered {
            get {
                return ResourceManager.GetString("LengthEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnSessionClose.
        /// </summary>
        public static string OnSessionClose {
            get {
                return ResourceManager.GetString("OnSessionClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet number is greater than total packets!.
        /// </summary>
        public static string PacketNumberIsGreater {
            get {
                return ResourceManager.GetString("PacketNumberIsGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PacketRequestId.
        /// </summary>
        public static string PacketRequestId {
            get {
                return ResourceManager.GetString("PacketRequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PacketType.
        /// </summary>
        public static string PacketType {
            get {
                return ResourceManager.GetString("PacketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProblemAddingAccount.
        /// </summary>
        public static string ProblemAddingAccount {
            get {
                return ResourceManager.GetString("ProblemAddingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProblemCreateNewAccountAndSession.
        /// </summary>
        public static string ProblemCreateNewAccountAndSession {
            get {
                return ResourceManager.GetString("ProblemCreateNewAccountAndSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProblemCreateServerSocket.
        /// </summary>
        public static string ProblemCreateServerSocket {
            get {
                return ResourceManager.GetString("ProblemCreateServerSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiveClientFromServer.
        /// </summary>
        public static string ReceiveClientFromServer {
            get {
                return ResourceManager.GetString("ReceiveClientFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiveData.
        /// </summary>
        public static string ReceiveData {
            get {
                return ResourceManager.GetString("ReceiveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceivedUnhandledCommand.
        /// </summary>
        public static string ReceivedUnhandledCommand {
            get {
                return ResourceManager.GetString("ReceivedUnhandledCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiveRequestOverTheLimit.
        /// </summary>
        public static string ReceiveRequestOverTheLimit {
            get {
                return ResourceManager.GetString("ReceiveRequestOverTheLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestSendData.
        /// </summary>
        public static string RequestSendData {
            get {
                return ResourceManager.GetString("RequestSendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunningCommand.
        /// </summary>
        public static string RunningCommand {
            get {
                return ResourceManager.GetString("RunningCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendTypeWithFunction.
        /// </summary>
        public static string SendTypeWithFunction {
            get {
                return ResourceManager.GetString("SendTypeWithFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerStartDateTime.
        /// </summary>
        public static string ServerStartDateTime {
            get {
                return ResourceManager.GetString("ServerStartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerTotalReceiveBytes.
        /// </summary>
        public static string ServerTotalReceiveBytes {
            get {
                return ResourceManager.GetString("ServerTotalReceiveBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerTotalReceivePacket.
        /// </summary>
        public static string ServerTotalReceivePacket {
            get {
                return ResourceManager.GetString("ServerTotalReceivePacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerTotalSendBytes.
        /// </summary>
        public static string ServerTotalSendBytes {
            get {
                return ResourceManager.GetString("ServerTotalSendBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerTotalSendPacket.
        /// </summary>
        public static string ServerTotalSendPacket {
            get {
                return ResourceManager.GetString("ServerTotalSendPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerUpTime.
        /// </summary>
        public static string ServerUpTime {
            get {
                return ResourceManager.GetString("ServerUpTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client is implemented as SSL. But the server without a certificate..
        /// </summary>
        public static string ServerWithOutCertificate {
            get {
                return ResourceManager.GetString("ServerWithOutCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StandardLength.
        /// </summary>
        public static string StandardLength {
            get {
                return ResourceManager.GetString("StandardLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartClientConnection.
        /// </summary>
        public static string StartClientConnection {
            get {
                return ResourceManager.GetString("StartClientConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartServer.
        /// </summary>
        public static string StartServer {
            get {
                return ResourceManager.GetString("StartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopServer.
        /// </summary>
        public static string StopServer {
            get {
                return ResourceManager.GetString("StopServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuccessAccountAdded.
        /// </summary>
        public static string SuccessAccountAdded {
            get {
                return ResourceManager.GetString("SuccessAccountAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuccessBindAndListenSocket.
        /// </summary>
        public static string SuccessBindAndListenSocket {
            get {
                return ResourceManager.GetString("SuccessBindAndListenSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuccessClientConnection.
        /// </summary>
        public static string SuccessClientConnection {
            get {
                return ResourceManager.GetString("SuccessClientConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuccessClientReceive.
        /// </summary>
        public static string SuccessClientReceive {
            get {
                return ResourceManager.GetString("SuccessClientReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuccessCreateServerSocket.
        /// </summary>
        public static string SuccessCreateServerSocket {
            get {
                return ResourceManager.GetString("SuccessCreateServerSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuccessfulOperation.
        /// </summary>
        public static string SuccessfulOperation {
            get {
                return ResourceManager.GetString("SuccessfulOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuccessRequestSendData.
        /// </summary>
        public static string SuccessRequestSendData {
            get {
                return ResourceManager.GetString("SuccessRequestSendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuccessUnpackingReceiveData.
        /// </summary>
        public static string SuccessUnpackingReceiveData {
            get {
                return ResourceManager.GetString("SuccessUnpackingReceiveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestNumber.
        /// </summary>
        public static string TestNumber {
            get {
                return ResourceManager.GetString("TestNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalSessionFromStartServerCount.
        /// </summary>
        public static string TotalSessionFromStartServerCount {
            get {
                return ResourceManager.GetString("TotalSessionFromStartServerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnhandledCommand.
        /// </summary>
        public static string UnhandledCommand {
            get {
                return ResourceManager.GetString("UnhandledCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitForConnection.
        /// </summary>
        public static string WaitForConnection {
            get {
                return ResourceManager.GetString("WaitForConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
