//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G9Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("G9Common.Resource.LogMessage", typeof(LogMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه کردن اکانت.
        /// </summary>
        public static string AccountAdded {
            get {
                return ResourceManager.GetString("AccountAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکانت و نشست با موفقیت ایجاد شد..
        /// </summary>
        public static string AccountAndSessionCreated {
            get {
                return ResourceManager.GetString("AccountAndSessionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامتر درست نیست!.
        /// </summary>
        public static string ArgumentNotCorrect {
            get {
                return ResourceManager.GetString("ArgumentNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامتر &apos;{0}&apos; به درستی وارد نشده است!.
        /// </summary>
        public static string ArgumentXNotCorrect {
            get {
                return ResourceManager.GetString("ArgumentXNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدنه.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز بافر.
        /// </summary>
        public static string BufferSize {
            get {
                return ResourceManager.GetString("BufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد منحصر به فرد کلاینت.
        /// </summary>
        public static string ClientSessionIdentity {
            get {
                return ResourceManager.GetString("ClientSessionIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دلیل بسته شدن.
        /// </summary>
        public static string CloseReason {
            get {
                return ResourceManager.GetString("CloseReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمان.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول (تعداد کاراکتر ها) کامند وارد شده از مقدار مجاز بیشتر است.
        /// </summary>
        public static string CommandLengthError {
            get {
                return ResourceManager.GetString("CommandLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساخت و مقدار دهی اولیه کلاینت.
        /// </summary>
        public static string CreateAndInitializeClient {
            get {
                return ResourceManager.GetString("CreateAndInitializeClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساخت و مقدار دهی اولیه سرور.
        /// </summary>
        public static string CreateAndInitializeServer {
            get {
                return ResourceManager.GetString("CreateAndInitializeServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساخت اکانت جدید.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول داده.
        /// </summary>
        public static string DataLength {
            get {
                return ResourceManager.GetString("DataLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در روند اجرای کامند خطایی رخ داده است..
        /// </summary>
        public static string ErrorInRunningCommand {
            get {
                return ResourceManager.GetString("ErrorInRunningCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در روند آماده سازی انتظار سرور برای اتصال کلایت مشکلی پیش آمده است.
        /// </summary>
        public static string FailBindAndListenSocket {
            get {
                return ResourceManager.GetString("FailBindAndListenSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در روند دریافت داده های ارسالی توسط کلاینت.
        /// </summary>
        public static string FailClientReceive {
            get {
                return ResourceManager.GetString("FailClientReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصال کلایت به سرور با خطا رو به رو شده است.
        /// </summary>
        public static string FailClinetConnection {
            get {
                return ResourceManager.GetString("FailClinetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ناموفق.
        /// </summary>
        public static string FailedOperation {
            get {
                return ResourceManager.GetString("FailedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در زمان ساخت بسته ارسالی خطا رخ داده است.
        /// </summary>
        public static string FailGeneratePacket {
            get {
                return ResourceManager.GetString("FailGeneratePacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در روند دریافت داده های ارسالی توسط سرور خطا رخ داده است.
        /// </summary>
        public static string FailReceiveClientFromServer {
            get {
                return ResourceManager.GetString("FailReceiveClientFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در روند ارسال داده خطا رخ داده است.
        /// </summary>
        public static string FailRequestSendData {
            get {
                return ResourceManager.GetString("FailRequestSendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حالت انتظار برای اتصال کانکشن مشکلی ایجاد شده است.
        /// </summary>
        public static string FailtOnWaitForConnection {
            get {
                return ResourceManager.GetString("FailtOnWaitForConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آی پی آدرس.
        /// </summary>
        public static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول (تعداد کاراکتر) وارد شده.
        /// </summary>
        public static string LengthEntered {
            get {
                return ResourceManager.GetString("LengthEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطع ارتباط یک کانکشن و بستن نشست.
        /// </summary>
        public static string OnSessionClose {
            get {
                return ResourceManager.GetString("OnSessionClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آی دی منحصر به فرد بسته.
        /// </summary>
        public static string PacketRequestId {
            get {
                return ResourceManager.GetString("PacketRequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع بسته.
        /// </summary>
        public static string PacketType {
            get {
                return ResourceManager.GetString("PacketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پورت.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکل در روند اضافه کردن اکانت به مجموعه.
        /// </summary>
        public static string ProblemAddingAccount {
            get {
                return ResourceManager.GetString("ProblemAddingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکل در روند ساخت اکانت و نشست.
        /// </summary>
        public static string ProblemCreateNewAccountAndSession {
            get {
                return ResourceManager.GetString("ProblemCreateNewAccountAndSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکل در روند ساخت سوکت.
        /// </summary>
        public static string ProblemCreateServerSocket {
            get {
                return ResourceManager.GetString("ProblemCreateServerSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع روند دریافت داده های ارسالی توسط سرور.
        /// </summary>
        public static string ReceiveClientFromServer {
            get {
                return ResourceManager.GetString("ReceiveClientFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست ارسال دیتا.
        /// </summary>
        public static string RequestSendData {
            get {
                return ResourceManager.GetString("RequestSendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کامند در حال اجرا.
        /// </summary>
        public static string RunningCommand {
            get {
                return ResourceManager.GetString("RunningCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول (تعداد کاراکتر) مجاز.
        /// </summary>
        public static string StandardLength {
            get {
                return ResourceManager.GetString("StandardLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع اتصال کلاینت به سرور.
        /// </summary>
        public static string StartClientConnection {
            get {
                return ResourceManager.GetString("StartClientConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع کار سرور.
        /// </summary>
        public static string StartServer {
            get {
                return ResourceManager.GetString("StartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکانت با موفقیت به مجموعه اضافه شد.
        /// </summary>
        public static string SuccessAccountAdded {
            get {
                return ResourceManager.GetString("SuccessAccountAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روند آماده سازی سرور برای انتظار ارتباط کلایت با موفقیت انجام شد.
        /// </summary>
        public static string SuccessBindAndListenSocket {
            get {
                return ResourceManager.GetString("SuccessBindAndListenSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصال کلاینت به سرور با موقیت برقرار شد.
        /// </summary>
        public static string SuccessClientConnection {
            get {
                return ResourceManager.GetString("SuccessClientConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده های ارسالی توسط کلاینت با موفقیت دریافت شد.
        /// </summary>
        public static string SuccessClientReceive {
            get {
                return ResourceManager.GetString("SuccessClientReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساخت موفقیت آمیز سوکت.
        /// </summary>
        public static string SuccessCreateServerSocket {
            get {
                return ResourceManager.GetString("SuccessCreateServerSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات موفق.
        /// </summary>
        public static string SuccessfulOperation {
            get {
                return ResourceManager.GetString("SuccessfulOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال داده با موفقیت انجام شد.
        /// </summary>
        public static string SuccessRequestSendData {
            get {
                return ResourceManager.GetString("SuccessRequestSendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده های دریافتی با آنالیز و به بسته مورد نیاز تبدیل شد.
        /// </summary>
        public static string SuccessUnpackingReceiveData {
            get {
                return ResourceManager.GetString("SuccessUnpackingReceiveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حالت انتظار برای اتصال یک کانکشن(کلاینت).
        /// </summary>
        public static string WaitForConnection {
            get {
                return ResourceManager.GetString("WaitForConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال انتظار.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
    }
}
